### ISSUE TITLE
Где уроки?

### ISSUE THREAD

**Issue by NMelis** [adv4000/terraform-lessons#1]
Привет, Денис, я вижу что тут в гите готов https://github.com/adv4000/terraform-lessons/tree/master/Lesson-11 ), а на ютубе этого нету, или все это сначала в партоны? или еще не смонтировал?

**Comment by adv4000** [comment]
Все уроки тут: https://www.udemy.com/rus-terraform/?couponCode=ADV-IT-RUS-TERRAFORM
